// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartShoppingAssistant.DataAcces;

#nullable disable

namespace SmartShoppingAssistant.DataAcces.Migrations
{
    [DbContext(typeof(SmartShoppingAssistantDbContext))]
    [Migration("20260511202536_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CategoryProduct");

                    b.HasData(
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 1
                        },
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 2
                        },
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 3
                        },
                        new
                        {
                            CategoriesId = 3,
                            ProductsId = 4
                        },
                        new
                        {
                            CategoriesId = 5,
                            ProductsId = 5
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 6
                        },
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 7
                        },
                        new
                        {
                            CategoriesId = 4,
                            ProductsId = 8
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAcces.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItem", (string)null);
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAcces.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Milk, cheese, yogurt",
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dried pasta, rice, and grain products",
                            Name = "Pasta & Grains"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fresh and processed meat products",
                            Name = "Meat"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Fresh and frozen vegetables",
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Water, juice, and soft drinks",
                            Name = "Beverages"
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAcces.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Classic Italian spaghetti, 500g",
                            ImageUrl = "/images/spaghetti.jpg",
                            Name = "Spaghetti",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Aged parmesan, 200g block",
                            ImageUrl = "/images/parmesan.jpg",
                            Name = "Parmesan Cheese",
                            Price = 12.50m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fresh whole milk, 1L",
                            ImageUrl = "/images/milk.jpg",
                            Name = "Whole Milk",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Fresh chicken breast, 500g",
                            ImageUrl = "/images/chicken.jpg",
                            Name = "Chicken Breast",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Still mineral water, 1.5L",
                            ImageUrl = "/images/water.jpg",
                            Name = "Mineral Water",
                            Price = 2.99m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Whole grain brown rice, 1kg",
                            ImageUrl = "/images/rice.jpg",
                            Name = "Brown Rice",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Creamy Greek yogurt, 400g",
                            ImageUrl = "/images/yogurt.jpg",
                            Name = "Greek Yogurt",
                            Price = 6.49m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Fresh ripe tomatoes, 500g",
                            ImageUrl = "/images/tomatoes.jpg",
                            Name = "Tomatoes",
                            Price = 3.99m
                        });
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAcces.Entities.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Reward")
                        .HasColumnType("int");

                    b.Property<int>("RewardValue")
                        .HasColumnType("int");

                    b.Property<decimal>("Threshold")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("Promotions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Buy 5 Get 1 Free Spaghetti",
                            ProductId = 1,
                            Reward = 0,
                            RewardValue = 1,
                            Threshold = 5m,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "10% off orders over 100 RON",
                            Reward = 1,
                            RewardValue = 10,
                            Threshold = 100.00m,
                            Type = 1
                        });
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("SmartShoppingAssistant.DataAcces.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartShoppingAssistant.DataAcces.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAcces.Entities.CartItem", b =>
                {
                    b.HasOne("SmartShoppingAssistant.DataAcces.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAcces.Entities.Promotion", b =>
                {
                    b.HasOne("SmartShoppingAssistant.DataAcces.Entities.Category", "Category")
                        .WithMany("Promotions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartShoppingAssistant.DataAcces.Entities.Product", "Product")
                        .WithMany("Promotions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAcces.Entities.Category", b =>
                {
                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("SmartShoppingAssistant.DataAcces.Entities.Product", b =>
                {
                    b.Navigation("Promotions");
                });
#pragma warning restore 612, 618
        }
    }
}
